-- AlterTable
ALTER TABLE `permission` MODIFY `code` ENUM('VIEW_DASHBOARD', 'VIEW_ANNOUNCEMENT', 'MANAGE_CHILDREN', 'MANAGE_PARENTS', 'MANAGE_IMMUNIZATION', 'MANAGE_VACCINES', 'MANAGE_USERS', 'MANAGE_ROLES', 'MANAGE_ADMINISTRATION') NOT NULL;
