-- CreateEnum
CREATE TYPE "ImmunizationStatus" AS ENUM ('PENDING', 'COMPLETED', 'SKIPPED', 'CANCELLED');

-- AlterTable
ALTER TABLE "ImmunizationRecord"
ADD COLUMN "administeredAt" TEXT,
ADD COLUMN "batchNumber" TEXT,
ADD COLUMN "doseNumber" INTEGER,
ADD COLUMN "isLate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "isMissed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "manufacturer" TEXT,
ADD COLUMN "nextDueDate" TIMESTAMP(3),
ADD COLUMN "remarks" TEXT,
ADD COLUMN "status" "ImmunizationStatus" NOT NULL DEFAULT 'PENDING',
ADD COLUMN "visitId" INTEGER,
ALTER COLUMN "dateGiven" DROP NOT NULL,
ALTER COLUMN "administeredBy" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Vaccine"
ADD COLUMN "boosterAfterMonths" INTEGER,
ADD COLUMN "requiresBooster" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "totalDoses" INTEGER;

-- CreateTable
CREATE TABLE "ImmunizationSchedule" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "vaccineId" INTEGER NOT NULL,
    "doseLabel" TEXT NOT NULL,
    "doseNumber" INTEGER NOT NULL,
    "recommendedAgeInMonths" INTEGER NOT NULL,
    "intervalDays" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ImmunizationSchedule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ImmunizationVisit" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "childId" INTEGER NOT NULL,
    "visitDate" TIMESTAMP(3) NOT NULL,
    "location" TEXT,
    "nurseName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ImmunizationVisit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ImmunizationSummary" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "childId" INTEGER NOT NULL,
    "totalRequired" INTEGER NOT NULL,
    "totalCompleted" INTEGER NOT NULL,
    "totalMissed" INTEGER NOT NULL,
    "completionRate" DOUBLE PRECISION NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ImmunizationSummary_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ImmunizationSummary_childId_key" ON "ImmunizationSummary"("childId");

-- AddForeignKey
ALTER TABLE "ImmunizationSchedule" ADD CONSTRAINT "ImmunizationSchedule_vaccineId_fkey" FOREIGN KEY ("vaccineId") REFERENCES "Vaccine"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ImmunizationVisit" ADD CONSTRAINT "ImmunizationVisit_childId_fkey" FOREIGN KEY ("childId") REFERENCES "Child"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ImmunizationRecord" ADD CONSTRAINT "ImmunizationRecord_visitId_fkey" FOREIGN KEY ("visitId") REFERENCES "ImmunizationVisit"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ImmunizationSummary" ADD CONSTRAINT "ImmunizationSummary_childId_fkey" FOREIGN KEY ("childId") REFERENCES "Child"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
